CREATE TABLE IF NOT EXISTS Path (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PATH TEXT
);

CREATE TABLE IF NOT EXISTS IP_Add (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    REMOTE_ADDR TEXT
);

CREATE TABLE IF NOT EXISTS Method (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    METHOD TEXT
);

CREATE TABLE IF NOT EXISTS HOST (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HOST TEXT
);

CREATE TABLE IF NOT EXISTS Agent (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_AGENT TEXT
);

CREATE TABLE IF NOT EXISTS ENCODING (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ENCODING TEXT
);

CREATE TABLE IF NOT EXISTS Accept (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCEPT TEXT
);

CREATE TABLE IF NOT EXISTS Language (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LANGUAGE TEXT
);

CREATE TABLE IF NOT EXISTS RealtimeLogs (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Date_time TIMESTAMP,
    IP_id INTEGER,
    Method_id INTEGER,
    Path_id INTEGER,
    Host_id INTEGER,
    USER_AGENT_id INTEGER,
    Accept_id INTEGER,
    Language_id INTEGER,
    Encoding_id INTEGER,
    OTHER_HEADER TEXT,
    Body TEXT,
    Suspicious INTEGER,
    FOREIGN KEY (IP_id) REFERENCES IP_Add(ID),
    FOREIGN KEY (Method_id) REFERENCES Method(ID),
    FOREIGN KEY (Path_id) REFERENCES Path(ID),
    FOREIGN KEY (Host_id) REFERENCES HOST(ID),
    FOREIGN KEY (USER_AGENT_id) REFERENCES Agent(ID),
    FOREIGN KEY (Accept_id) REFERENCES Accept(ID),
    FOREIGN KEY (Language_id) REFERENCES Language(ID),
    FOREIGN KEY (Encoding_id) REFERENCES ENCODING(ID)
);
